// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: follow_feed.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createFollowedFeed = `-- name: CreateFollowedFeed :one
INSERT INTO followed_feeds (id, created_at, updated_at, user_id, feed_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, created_at, updated_at, user_id, feed_id
`

type CreateFollowedFeedParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	FeedID    uuid.UUID
}

func (q *Queries) CreateFollowedFeed(ctx context.Context, arg CreateFollowedFeedParams) (FollowedFeed, error) {
	row := q.db.QueryRowContext(ctx, createFollowedFeed,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UserID,
		arg.FeedID,
	)
	var i FollowedFeed
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.FeedID,
	)
	return i, err
}

const deleteFollowedFeed = `-- name: DeleteFollowedFeed :exec
DELETE FROM followed_feeds WHERE id = $1 AND user_id = $2
`

type DeleteFollowedFeedParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteFollowedFeed(ctx context.Context, arg DeleteFollowedFeedParams) error {
	_, err := q.db.ExecContext(ctx, deleteFollowedFeed, arg.ID, arg.UserID)
	return err
}

const getFollowedFeedsByUserID = `-- name: GetFollowedFeedsByUserID :many
SELECT id, created_at, updated_at, user_id, feed_id FROM followed_feeds WHERE user_id = $1
`

func (q *Queries) GetFollowedFeedsByUserID(ctx context.Context, userID uuid.UUID) ([]FollowedFeed, error) {
	rows, err := q.db.QueryContext(ctx, getFollowedFeedsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FollowedFeed
	for rows.Next() {
		var i FollowedFeed
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.FeedID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
