package main

import (
	"time"

	"github.com/google/uuid"
	"github.com/justWeird/GO-RSS-AGG/internal/database"
)

// create a struct to represent the user model, which will be used to decode the JSON request body
// and also to send the response back to the client.
type User struct {
	ID        uuid.UUID `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	Name      string    `json:"name"`
	APIKey    string    `json:"apikey,omitempty"` // include the API key in the response, but omit it if it's empty
}

type Feed struct {
	ID        uuid.UUID `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	Name      string    `json:"name"`
	URL       string    `json:"url"`
	UserID    uuid.UUID `json:"user_id"`
}

type FollowedFeed struct {
	ID        uuid.UUID `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	UserID    uuid.UUID `json:"user_id"`
	FeedID    uuid.UUID `json:"feed_id"`
}

// convert the database.User struct generated by sqlc to our User struct defined above,
// which includes JSON tags for proper encoding and decoding of JSON data.
func dbUserToUser(dbUser database.User) User {
	return User{
		ID:        dbUser.ID,
		CreatedAt: dbUser.CreatedAt,
		UpdatedAt: dbUser.UpdatedAt,
		Name:      dbUser.Name,
		APIKey:    dbUser.Apikey,
	}
}

func dbFeedToFeed(dbFeed database.Feed) Feed {
	return Feed{
		ID:        dbFeed.ID,
		CreatedAt: dbFeed.CreatedAt,
		UpdatedAt: dbFeed.UpdatedAt,
		Name:      dbFeed.Name,
		URL:       dbFeed.Url,
		UserID:    dbFeed.UserID,
	}
}

func dbFeedsToFeeds(dbFeeds []database.Feed) []Feed {
	feeds := []Feed{} //initialize an empty slice to hold the converted feeds

	for _, dbFeed := range dbFeeds {
		feeds = append(feeds, dbFeedToFeed(dbFeed)) // convert each database feed to our Feed struct and append it to the feeds slice
	}

	return feeds
}

func dbFollowedFeedToFollowedFeed(dbFollowedFeed database.FollowedFeed) FollowedFeed {
	return FollowedFeed{
		ID:        dbFollowedFeed.ID,
		CreatedAt: dbFollowedFeed.CreatedAt,
		UpdatedAt: dbFollowedFeed.UpdatedAt,
		UserID:    dbFollowedFeed.UserID,
		FeedID:    dbFollowedFeed.FeedID,
	}
}

func dbFollowedFeedsToFollowedFeeds(dbFollowedFeeds []database.FollowedFeed) []FollowedFeed {
	followedFeeds := []FollowedFeed{} //initialize an empty slice to hold the converted followed feeds

	for _, dbFollowedFeed := range dbFollowedFeeds {
		// convert each database followed feed to our FollowedFeed struct and append it to the followedFeeds slice
		followedFeeds = append(followedFeeds, dbFollowedFeedToFollowedFeed(dbFollowedFeed))
	}
	return followedFeeds
}
