package main

import (
	"time"

	"github.com/google/uuid"
	"github.com/justWeird/GO-RSS-AGG/internal/database"
)

// create a struct to represent the user model, which will be used to decode the JSON request body
// and also to send the response back to the client.
type User struct {
	ID        uuid.UUID `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	Name      string    `json:"name"`
	APIKey    string    `json:"apikey,omitempty"` // include the API key in the response, but omit it if it's empty
}

// convert the database.User struct generated by sqlc to our User struct defined above,
// which includes JSON tags for proper encoding and decoding of JSON data.
func dbUserToUser(dbUser database.User) User {
	return User{
		ID:        dbUser.ID,
		CreatedAt: dbUser.CreatedAt,
		UpdatedAt: dbUser.UpdatedAt,
		Name:      dbUser.Name,
		APIKey:    dbUser.Apikey,
	}
}
